export const branches = [
    { value: 'open-source', label: 'Open Source' },
    { value: 'competitive-programming', label: 'Competitive Programming' },
    { value: 'machine-learning', label: 'Machine Learning' },
    { value: 'web-&-app', label: 'Web & App Dev' },
    { value: 'cyber-security', label: 'Cyber Security' },
    { value: 'publicity-&-design', label: 'Publicity & Design' },
];

export const branch_info = [
    { name: "open-source", logo: "https://firebasestorage.googleapis.com/v0/b/pec-acm-website.appspot.com/o/os.png?alt=media&token=0954f9f8-df45-41f4-94f8-9b4d3f511679"},
    { name: "competitive-programming", logo: "https://firebasestorage.googleapis.com/v0/b/pec-acm-website.appspot.com/o/cp.png?alt=media&token=3074bd77-9689-406f-b5a5-fee93e77a4be", info: "Competitive programming is a mind sport that involves solving algorithmic problems within a time limit. Participants use their coding skills to come up with the most efficient solution and compete against other programmers. ACM-CSS provides resources including important questions and upcoming cp contests. It also has its cp discussion channel on discord where members can ask their doubts and the problems are solved collectively. Discussions can help members identify more efficient algorithms or optimizations that they may have missed. As in the end main purpose of cp is to give a better understanding of the problem and more effective problem-solving strategies."},
    { name: "machine-learning", logo: "https://firebasestorage.googleapis.com/v0/b/pec-acm-website.appspot.com/o/ml.png?alt=media&token=f53a233e-5694-4e7d-8de0-73d443142c56", info: "Machine learning (ML) is a subset of artificial intelligence (AI) that enables software applications to grow increasingly effective at predicting outcomes without explicitly programming them to do so. Machine learning is a broad approach that contains numerous libraries and allows programmers to do a variety of things with it, such as heart disease prediction, weather prediction, and much more. Machine Learning has now become a necessary and crucial ability for programmers to learn in order to create effective projects like ChatGPT or Any Automatic Projects. Our Club ACM makes machine learning easy and entertaining to study by hosting numerous challenges on many platforms, such as Weekly Kaggle Challenges, and by hosting other engaging sessions in which students may discuss their dobuts and ideas."},
    { name: "web-&-app", logo: "https://firebasestorage.googleapis.com/v0/b/pec-acm-website.appspot.com/o/web.png?alt=media&token=0ae7e08e-e380-46eb-83b3-41436bb09435", info: "Web application development is the creation of application programs that reside on remote servers and are delivered to the user’s device over the Internet. A web application (web app) does not need to be downloaded and is instead accessed through a network. An end user can access a web application through a web browser such as Google Chrome, Safari, or Mozilla Firefox. A majority of web applications can be written in JavaScript, Cascading Style Sheets (CSS), and HTML5."},
    { name: "cyber-security", logo: "https://firebasestorage.googleapis.com/v0/b/pec-acm-website.appspot.com/o/cyber.png?alt=media&token=89d523a0-62d0-43e1-a30b-24792e7fe757", info: "Cybersecurity is a constantly evolving field that seeks to protect computer systems, networks, and sensitive information from unauthorised access, theft, and damage. Cybersecurity involves some important topics like: Importance of strong passwords and password management, Two-factor authentication and multi-factor authentication, Malware, viruses, and ransomware, Network security and firewalls, Data encryption and decryption techniques, Internet of Things (IoT) security, etc. It's important to stay up-to-date with the latest cybersecurity news and trends, as new threats and attack techniques are constantly emerging. The cybersecurity subgroup of PEC ACM-CSS focuses on cybersecurity education and research. The ACM CSS also provides resources and opportunities for students interested in cybersecurity, including competitions, workshops, and mentorship programs. ACM CSS also hosts events where students can network with professionals in the field and gain hands-on experience with cutting-edge cybersecurity technologies. So, have a break, have cyber."},
    { name: "publicity-&-design", logo: "https://firebasestorage.googleapis.com/v0/b/pec-acm-website.appspot.com/o/socials.png?alt=media&token=c7f0762a-0d1e-4bb7-a4da-d35005263a77", info: "Any event, Hackathon, Coding contest can only be competitive if it has reached maximum interested audience. Introducing Publicity and Design, our Aim is to create the greatest hype and vibe through publicizing both Online and Offline, keeping the spirits high and engaging maximum peers. Creating magnetic Designs to attract the audience using our creativity for posts, captions and content writing. Online - We mostly use Canva to provide PEC ACM with a large engaging audience in each and every way possible.Offline - Word-to-word, hall-to-hall publicity, banners, posters etc. Are also used and last but not the least, Our work though less technical but hugely Impactful."},
];